server:
  port: 8080
spring:
  application:
    name: mybatis-plus-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/demo?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: postgres
    password: postgres
  # 配置连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
  # 解决jackson序列化的时区(-8)
  jackson:
    time-zone: GMT+8
# 配置swagger
swagger:
  base-package: com.gjing.project.mybatisplus
  title: Mybatis-Plus小Demo
mybatis-plus:
  global-config:
  # 排除恶心的banner
    banner: false
  # 配置逻辑删除
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
  # 枚举扫描包
  type-enums-package: com.gjing.project.mybatisplus.enums
  # xml文件路径
  mapper-locations: classpath:/mappers/*.xml
